version: '3.1'

services:

  mysql_db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'technical_test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    volumes:
      - db:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    command: ['php', 'artisan', 'serve', '--host', '0.0.0.0']
    ports:
      - 8000:8000
    depends_on:
      - mysql_db

volumes:
  db:
